apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mirror-60b5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mirror-60b5"
  template:
    metadata:
      labels:
        app: "mirror-60b5"
    spec:
      containers:
        - name: "mirror-60b5"
          image: "chamith.azurecr.io/mirror"
          ports:
          - containerPort: 80