apiVersion: v1
kind: Service
metadata:
    name: "mirrorbot-4810"
    labels:
        app: "mirrorbot-4810"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mirrorbot-4810"